name: Publish preview

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: "reason"
        required: false
        type: text

jobs:
  deploy:
    environment: secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tocit/s3-sync-with-cloudfront-invalidation@verze1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          DISTRIBUTION_ID: "E3ABKG4QXPTL3P"
          AWS_REGION: "eu-central-1" # optional: defaults to us-east-1
          SOURCE_DIR: "out" # optional: defaults to entire repository
          DEST_DIR: "zivot-k-nezaplaceni/out" # optional: defaults to the root of the bucket
